# simplelogger.properties
# see https://www.slf4j.org/apidocs/org/slf4j/simple/SimpleLogger.html
org.slf4j.simpleLogger.defaultLogLevel=DEBUG
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.dateTimeFormat=YYYY-MM-dd HH:mm:ss.SSS
org.slf4j.simpleLogger.levelInBrackets=true
# hide extra prefix parts: thread, logger name, short name, and level
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false
org.slf4j.simpleLogger.showShortLogName=false
org.slf4j.simpleLogger.showLevel=false
# less jetty noise
org.slf4j.simpleLogger.log.org.eclipse.jetty=INFO
# more javalin noise
org.slf4j.simpleLogger.log.io.javalin=TRACE
# less Hikari noise
org.slf4j.simpleLogger.log.com.zaxxer.hikari=INFO
# a lot less jOOQ noise
org.slf4j.simpleLogger.log.org.jooq=WARN
# custom noise for our app
org.slf4j.simpleLogger.log.org.cytraining.backend=INFO